[build]
  publish = "Blog-DevInit/public"
  command = "cd Blog-DevInit && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://devinit.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
